:ruby: ree187
:application: moonwalk
:user: rails
#:time_zone: UTC
:deploy_to: /var/www/apps/moonwalk
:domain: moonwalkcardio.com
:domain_aliases:
  - www.moonwalkcardio.com
  - moonwalkcardio.net
  - www.moonwalkcardio.net
  - www.moonwalkcardio.org
  - moonwalkcardio.org
  - moonwalkcardioantigravitycenter.com
  - moonwalkcardioantigravitycenter.net
  - moonwalk.cube2media.com

:repository: git@github.com:electricgraffitti/moonwalk.git
:branch: master

# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
:app_symlinks:
  - photos
  - attachments
  - videos
#
# Use :local_config to copy directories straight from your local project directory
# to the server: these are files that you don't have/want in scm.
:local_config:
  - config/database.yml
#
# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- config
# After specifying a gem with config.gem, run 'rake moonshine:gems'
# to update config/gems.yml. If the gem depends on native packages, 
# tell Moonshine here:
:apt_gems:
  :paperclip:
    - imagemagick
  #    - libawesome-dev
#
# See all the options for Passenger, Apache vhosts, and MySQL in the
# respective templates: moonshine/lib/moonshine/manifest/rails/templates
:passenger:
  :max_pool_size: 2
  :use_global_queue: true
  :version: 2.2.15
:mysql:
  :innodb_buffer_pool_size: 32M

